import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
    default: "Default title",
    template: "%s | Default title",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="px-2 py-3 bg-blue-400 text-center">
          <Link className="px-2 text-2xl" href={"/"}>
            Home
          </Link>
          <Link className="px-2 text-2xl" href={"about"}>
            About
          </Link>
          <Link className="px-2 text-2xl" href={"/products"}>
            Products
          </Link>
          <Link className="px-2 text-2xl" href={"/profile"}>
            Profile
          </Link>
        </header>
        <main className="p-4 bg-gray-300 min-h-screen text-black">
          {children}
        </main>
        <footer className="px-2 py-3 bg-black text-center">Footer</footer>
      </body>
    </html>
  );
}
